# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Node JS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: ./
  deploy:
    runs-on: ubuntu-latest
    needs: build
    container: 
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: install cURL
        run: apk --no-cache add curl
      - name: install zip
        run: apk --no-cache add zip
      - name: install bash
        run: apk add --no-cache bash
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: release
          path: site/
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          directory: site
      - name: move release.zip
        run: mv ./site/release.zip release.zip
      - name: deploynator
        env:
          HTTP_DEPLOY_URL: ${{secrets.HTTP_DEPLOY_URL}}
          HTTP_DEPLOY_TOKEN: ${{secrets.HTTP_DEPLOY_TOKEN}}
        run: curl -X POST $HTTP_DEPLOY_URL --form "token=$HTTP_DEPLOY_TOKEN" --form "data=@release.zip;type=application/zip" --fail-with-body
      
